### ISSUE TITLE
startapp does not work

### ISSUE THREAD

**Issue by danieltatrai** [galaktika-solutions/gStack#27]
dc run --rm django django-admin startapp latex

Results:
Starting gstacktest-postgres ... done
Traceback (most recent call last):
  File "/python/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/python/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/python/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/python/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/django_project/core/settings.py", line 24, in <module>
    SECRET_KEY = read_secret('DJANGO_SECRET_KEY')
  File "/src/django_project/core/utils.py", line 9, in read_secret
    with open(os.path.join(SECRET_MOUNT, secret)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/run/secrets/DJANGO_SECRET_KEY'

File is there, with make bash. 400 permission, owner: django.

If you make bash in, django-admin startapp latex will error with the following:
CommandError: [Errno 13] Permission denied: '/src/django_project/latex'

**Comment by richardbann** [comment]
I will merge `gdockutils` soon, which solves this issue.

**Comment by richardbann** [comment]
I close it as irrelevant right now
